# fly.toml app configuration file generated for ham-bot-prod on 2023-11-29T10:55:52+01:00

app = "ham-bot-prod"
primary_region = "arn"

[build]
  dockerfile = "./apps/annie/Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[checks]
 [checks.annie_http_health]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/healthcheck"
    timeout = "10s"
    type = "http"
