name: CI

on: [pull_request]

env:
  CLICOLOR_FORCE: 1

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
      - name: Run CI
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: ci
